### ISSUE TITLE
Issue in Result page

### ISSUE THREAD

**Issue by syncinggreen** [r3curs1v3-pr0xy/vajra#14]
In between the Scan , I clicked on Result Page link and got the following error.

TypeError: /root/vajra/views/result.ejs:452
    450|             </thead>
    451|             <tbody style="background-color: #353c48; color: black;">
 >> 452|                 <% data.forEach((target)=>{%>
    453|                     <tr>
    454|                         <td>
    455|                             <form method="POST" action='/target/'>

data.forEach is not a function
    at eval (eval at compile (/root/vajra/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:15:13)
    at result (/root/vajra/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/root/vajra/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/root/vajra/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/root/vajra/node_modules/express/lib/view.js:135:8)
    at tryRender (/root/vajra/node_modules/express/lib/application.js:640:10)
    at Function.render (/root/vajra/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/root/vajra/node_modules/express/lib/response.js:1012:7)
    at /root/vajra/index.js:3037:25
    at ChildProcess.exithandler (child_process.js:299:7)

**Comment by r3curs1v3-pr0xy** [comment]
CouchDB is not installed properly in your OS. Which OS you're using?

**Comment by elixirop** [comment]
The same error forme
![Screenshot from 2021-03-25 17-30-50](https://user-images.githubusercontent.com/68217482/112560521-a51ed380-8d90-11eb-8aa2-5e048783365a.png)

 Ubuntu 20.04.2 LTS

**Comment by r3curs1v3-pr0xy** [comment]
This is due to couchdb is not installed properly. Use docker image of Vajra to avoid any errors
